# Generated by Django 2.1.7 on 2019-03-25 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('codigo', models.CharField(max_length=20)),
                ('tipo', models.CharField(max_length=20)),
                ('version', models.CharField(max_length=20)),
                ('fecha', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
